# fly.toml app configuration file generated for restore-ernabr-3 on 2023-12-18T20:04:49+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "restore-ernabr-3"
primary_region = "ams"

[build]
  image = "ernabr/restore:latest" 

[env]
  ASPNETCORE_URLS = "http://+:8080"
  StripeSettings__PublishableKey = "pk_test_51OMnkFFIaoBS7GQ3xlQ9glLpy5mF5D0dWmBTDijHZPNSzJImnj1COEPrc40q3ly6ffFSLBlmH1N1UNUKihu2WwpS00attsJIMn"
  Cloudinary__CloudName = "do80gbqjy"
  Cloudinary__ApiKey = "724838645844159"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
